// app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";
import Topbar from "./components/Topbar";
import Sidebar from "./components/Sidebar";

export const metadata: Metadata = {
  title: "User Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-full bg-[url(/useradmin/admin.jpg)] bg-cover">
          <Sidebar />
          <div className="ml-[233px] flex  flex-col flex-1 overflow-y-scroll">
            <Topbar />
            <main className="flex-1 overflow-hidden p-5">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
